/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oi;

import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/**
 *
 * @author 20181041110033
 */
public class Notepad extends javax.swing.JFrame {

    /**
     * Creates new form Notepad
     */
    public Notepad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        arquivo1 = new javax.swing.JMenuItem();
        arquivo2 = new javax.swing.JMenuItem();
        arquivo3 = new javax.swing.JMenuItem();
        arquivo4 = new javax.swing.JMenuItem();
        sair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        localizar = new javax.swing.JMenuItem();
        substituir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        fonte = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ferramentas = new javax.swing.JMenuItem();
        status = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ajuda = new javax.swing.JMenuItem();
        notas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        texto.setColumns(20);
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        jMenu1.setText("Arquivo");

        arquivo1.setText("Novo Arquivo");
        arquivo1.setToolTipText("");
        jMenu1.add(arquivo1);

        arquivo2.setText("Abrir Arquivo");
        arquivo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivo2ActionPerformed(evt);
            }
        });
        jMenu1.add(arquivo2);

        arquivo3.setText("Salvar Arquivo");
        arquivo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivo3ActionPerformed(evt);
            }
        });
        jMenu1.add(arquivo3);

        arquivo4.setText("Fechar Arquivo");
        jMenu1.add(arquivo4);

        sair.setText("Sair");
        jMenu1.add(sair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        localizar.setText("Localizar");
        jMenu2.add(localizar);

        substituir.setText("Substituir");
        jMenu2.add(substituir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Formatar");

        fonte.setText("Fonte");
        fonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fonteActionPerformed(evt);
            }
        });
        jMenu3.add(fonte);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Exibir");

        ferramentas.setText("Barra de Ferramentas");
        jMenu4.add(ferramentas);

        status.setText("Barra de Status");
        jMenu4.add(status);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Ajuda");

        ajuda.setText("Exibir Ajuda");
        jMenu5.add(ajuda);

        notas.setText("Sobre o Bloco de Notas");
        jMenu5.add(notas);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arquivo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivo2ActionPerformed
        // TODO add your handling code here:
        JFileChooser abrir = new JFileChooser ();
        int opcao = abrir.showOpenDialog(this);
        if (opcao == JFileChooser.APPROVE_OPTION){
            texto.setText("");
            
            try {
                Scanner scan = new Scanner(new FileReader(abrir.getSelectedFile().getPath()));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_arquivo2ActionPerformed

    private void arquivo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivo3ActionPerformed
        // TODO add your handling code here:
        JFileChooser salvar = new JFileChooser ();
        int opcao = salvar.showSaveDialog(this);
        try {
            FileWriter arquivo = new FileWriter (salvar.getSelectedFile().getPath());
        } catch (IOException ex) {
            Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_arquivo3ActionPerformed

    private void fonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fonteActionPerformed
        // TODO add your handling code here:
        FormatarFonte fonte = new FormatarFonte(this, false);
        fonte.setVisible(true);
    }//GEN-LAST:event_fonteActionPerformed

    public JTextArea getTexto() {
        return texto;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ajuda;
    private javax.swing.JMenuItem arquivo1;
    private javax.swing.JMenuItem arquivo2;
    private javax.swing.JMenuItem arquivo3;
    private javax.swing.JMenuItem arquivo4;
    private javax.swing.JMenuItem ferramentas;
    private javax.swing.JMenuItem fonte;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem localizar;
    private javax.swing.JMenuItem notas;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem status;
    private javax.swing.JMenuItem substituir;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
